# Generated by Django 5.2.8 on 2025-11-08 14:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.CharField(help_text="命名空间唯一标识，如 'dev', 'prod', 'lab-instruments'", max_length=128, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='命名空间ID只能包含字母、数字、下划线和连字符', regex='^[a-zA-Z0-9_-]+$')])),
                ('name', models.CharField(help_text='命名空间显示名称', max_length=255)),
                ('description', models.TextField(blank=True, help_text='命名空间用途说明')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用（禁用后该命名空间下的所有AgentCard将不可见）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '命名空间',
                'verbose_name_plural': '命名空间',
                'db_table': 'namespaces',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchemaRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_uri', models.URLField(help_text='Schema URI（全球唯一标识符），如 https://my-org.com/schemas/physicalAsset/v1', max_length=512, unique=True)),
                ('schema_type', models.CharField(db_index=True, help_text="Schema 类型简称，如 'physicalAsset', 'hplc', 'financeBot'", max_length=128)),
                ('version', models.CharField(help_text="Schema 版本号，如 'v1', 'v1.2', 'v2.0'", max_length=32)),
                ('description', models.TextField(blank=True, help_text='Schema 用途说明（用于文档和 API）')),
                ('example_data', models.JSONField(blank=True, help_text='示例数据（可选，帮助开发者理解）', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schema定义',
                'verbose_name_plural': 'Schema定义',
                'db_table': 'schema_registry',
                'ordering': ['schema_type', '-version'],
                'indexes': [models.Index(fields=['schema_type', 'version'], name='schema_regi_schema__8b4715_idx'), models.Index(fields=['is_active'], name='schema_regi_is_acti_ac79c1_idx')],
                'unique_together': {('schema_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AgentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Agent 名称（在同一 namespace 内，name + version 唯一）', max_length=64, validators=[django.core.validators.RegexValidator(message='名称只能包含 ASCII 可打印字符（码位 32-126）', regex='^[\\x20-\\x7E]+$')])),
                ('version', models.CharField(help_text="Agent 版本号，建议使用语义化版本，如 '1.0.0', '2.1.3-beta'", max_length=32)),
                ('is_default_version', models.BooleanField(db_index=True, default=False, help_text='是否为默认发布版本（每个 namespace::name 只能有一个默认版本）')),
                ('protocol_version', models.CharField(default='0.3.0', help_text='A2A 协议版本号', max_length=16)),
                ('description', models.TextField(help_text='Agent 用途和领域说明（清晰描述其功能）')),
                ('url', models.URLField(help_text='主要端点 URL（必须使用 HTTPS）', max_length=512)),
                ('preferred_transport', models.CharField(choices=[('http', 'HTTP/REST'), ('grpc', 'gRPC'), ('websocket', 'WebSocket')], default='http', help_text='首选传输协议', max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text="AgentCapabilities 对象，如 {'streaming': true, 'tools': true, 'responseFormats': ['text', 'json']}")),
                ('default_input_modes', models.JSONField(default=list, help_text="支持的输入 MIME 类型数组，如 ['text/plain', 'application/json', 'image/png']")),
                ('default_output_modes', models.JSONField(default=list, help_text="支持的输出 MIME 类型数组，如 ['text/plain', 'application/json']")),
                ('skills', models.JSONField(default=list, help_text='AgentSkill 数组，每个 skill 包含: {name, description, inputModes?, outputModes?, parameters?}')),
                ('provider', models.JSONField(blank=True, help_text="AgentProvider 对象，如 {name: 'My Organization', url: 'https://my-org.com', email: 'contact@my-org.com'}", null=True)),
                ('icon_url', models.URLField(blank=True, help_text='Agent 图标 URL（建议使用 PNG/SVG，尺寸 256x256）', max_length=512, null=True)),
                ('documentation_url', models.URLField(blank=True, help_text='详细文档链接', max_length=512, null=True)),
                ('additional_interfaces', models.JSONField(blank=True, default=list, help_text="AgentInterface 数组（备选传输方式），如 [{transport: 'grpc', url: 'grpc://...'}]")),
                ('security_schemes', models.JSONField(blank=True, default=dict, help_text="认证方案定义（OpenAPI 风格），如 {apiKey: {type: 'apiKey', in: 'header', name: 'X-API-Key'}}")),
                ('security', models.JSONField(blank=True, default=list, help_text="安全要求数组（OR/AND 逻辑），如 [{apiKey: []}] 或 [{oauth: ['read', 'write']}]")),
                ('supports_authenticated_extended_card', models.BooleanField(default=False, help_text='是否支持认证后返回扩展卡（包含敏感信息）')),
                ('signatures', models.JSONField(blank=True, default=list, help_text='JWS 签名数组（用于 AgentCard 完整性验证）')),
                ('domain_extensions', models.JSONField(blank=True, default=dict, help_text="L2 领域扩展数据，使用 Schema URI 作为命名空间。\n格式: {schema_uri: {field: value, ...}, ...}\n示例: {'https://my-org.com/schemas/physicalAsset/v1': {'physicalAssetId': 'HPLC-001', 'locationId': 'Lab-A', 'status': 'OPERATIONAL'}}")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否激活（用于软删除或临时禁用）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='创建者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_cards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agent_cards', to=settings.AUTH_USER_MODEL)),
                ('namespace', models.ForeignKey(help_text='所属命名空间（用于环境/团队隔离）', on_delete=django.db.models.deletion.CASCADE, related_name='agent_cards', to='documents.namespace')),
            ],
            options={
                'verbose_name': 'AgentCard',
                'verbose_name_plural': 'AgentCards',
                'db_table': 'agent_cards',
                'ordering': ['namespace', 'name', '-version'],
                'indexes': [models.Index(fields=['namespace', 'name', 'is_default_version'], name='agent_cards_namespa_1a663b_idx'), models.Index(fields=['namespace', 'is_active'], name='agent_cards_namespa_8b4098_idx'), models.Index(fields=['created_at'], name='agent_cards_created_b20b65_idx'), models.Index(fields=['updated_at'], name='agent_cards_updated_644f58_idx')],
                'unique_together': {('namespace', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="字段名称（建议使用 camelCase，如 'physicalAssetId'）", max_length=128, validators=[django.core.validators.RegexValidator(message='字段名必须以字母开头，只能包含字母、数字和下划线', regex='^[a-zA-Z][a-zA-Z0-9_]*$')])),
                ('field_type', models.CharField(choices=[('string', '文本'), ('integer', '整数'), ('number', '数字（含小数）'), ('boolean', '布尔值'), ('array', '数组'), ('object', '对象'), ('datetime', '日期时间'), ('date', '日期'), ('enum', '枚举（单选）')], default='string', help_text='字段数据类型', max_length=32)),
                ('is_required', models.BooleanField(default=False, help_text='是否必填')),
                ('description', models.TextField(blank=True, help_text='字段说明（会显示在文档和 API 中）')),
                ('default_value', models.JSONField(blank=True, help_text='默认值（JSON 格式）', null=True)),
                ('min_length', models.IntegerField(blank=True, help_text='最小长度（仅 string 类型）', null=True)),
                ('max_length', models.IntegerField(blank=True, help_text='最大长度（仅 string 类型）', null=True)),
                ('min_value', models.FloatField(blank=True, help_text='最小值（仅 integer/number 类型）', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='最大值（仅 integer/number 类型）', null=True)),
                ('enum_choices', models.JSONField(blank=True, help_text="枚举值列表（仅 enum 类型），如 ['OPERATIONAL', 'MAINTENANCE', 'OFFLINE']", null=True)),
                ('pattern', models.CharField(blank=True, help_text="正则表达式模式（仅 string 类型），如 '^[A-Z]{2,4}-\\d{3}$'", max_length=512)),
                ('order', models.IntegerField(default=0, help_text='显示顺序（越小越靠前）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(help_text='所属 Schema', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.schemaregistry')),
            ],
            options={
                'verbose_name': 'Schema字段',
                'verbose_name_plural': 'Schema字段',
                'db_table': 'schema_fields',
                'ordering': ['schema', 'order', 'field_name'],
                'unique_together': {('schema', 'field_name')},
            },
        ),
    ]
