# Generated by Django 5.2.8 on 2025-11-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_database_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcard',
            name='capability_push_notifications',
            field=models.BooleanField(default=False, help_text='是否支持推送通知'),
        ),
        migrations.AddField(
            model_name='agentcard',
            name='capability_state_transition_history',
            field=models.BooleanField(default=False, help_text='是否提供状态转换历史'),
        ),
        migrations.AddField(
            model_name='agentcard',
            name='capability_streaming',
            field=models.BooleanField(default=False, help_text='是否支持 SSE 流式响应（A2A 协议 5.5.2）'),
        ),
        migrations.AlterField(
            model_name='agentcard',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='[已废弃] 旧的 capabilities 字段，数据已迁移到 capability_* 字段和 AgentExtension 模型'),
        ),
        migrations.AlterField(
            model_name='agentcard',
            name='domain_extensions',
            field=models.JSONField(blank=True, default=dict, help_text='[已废弃] 旧的 domainExtensions 字段，数据已迁移到 AgentExtension 模型。\n新设计符合 A2A 协议标准，使用 AgentCapabilities.extensions[] 存储。'),
        ),
        migrations.CreateModel(
            name='AgentExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(help_text='扩展的唯一标识 URI。\n- 协议扩展：如 https://a2a.org/extensions/streaming-v2\n- 领域数据：如 https://lab.com/schemas/physicalAsset/v1', max_length=512)),
                ('description', models.TextField(blank=True, help_text='扩展说明（可选）。\n可以从 SchemaRegistry 自动填充，也可以手动定制。')),
                ('required', models.BooleanField(default=False, help_text='客户端是否必须理解此扩展（通常为 false）')),
                ('params', models.JSONField(blank=True, default=dict, help_text='扩展参数（JSON 对象）。\n- 协议扩展：配置参数，如 {"maxStreams": 5}\n- 领域数据：完整的业务数据，如 {"assetId": "HPLC-001", "status": "OPERATIONAL"}')),
                ('order', models.IntegerField(default=0, help_text='显示顺序（数字越小越靠前）')),
                ('agent_card', models.ForeignKey(help_text='所属 AgentCard', on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='documents.agentcard')),
                ('schema', models.ForeignKey(blank=True, help_text='关联的 Schema 定义（用于验证 params 结构）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_extensions', to='documents.schemaregistry')),
            ],
            options={
                'verbose_name': 'Agent扩展',
                'verbose_name_plural': 'Agent扩展',
                'db_table': 'agent_extensions',
                'ordering': ['agent_card', 'order', 'uri'],
                'indexes': [models.Index(fields=['agent_card', 'uri'], name='agent_exten_agent_c_a63c26_idx')],
                'unique_together': {('agent_card', 'uri')},
            },
        ),
    ]
