# Generated by Django 5.2.8 on 2025-11-09 07:56

from django.db import migrations


def migrate_to_extensions_forward(apps, schema_editor):
    """
    将 domain_extensions 和 capabilities JSONField 数据迁移到新结构
    """
    AgentCard = apps.get_model('documents', 'AgentCard')
    AgentExtension = apps.get_model('documents', 'AgentExtension')
    SchemaRegistry = apps.get_model('documents', 'SchemaRegistry')

    # 建立 schema_uri 到 SchemaRegistry 的映射
    schema_map = {
        schema.schema_uri: schema
        for schema in SchemaRegistry.objects.all()
    }

    migrated_count = 0
    error_count = 0

    for card in AgentCard.objects.all():
        # 1. 迁移 capabilities 布尔字段
        old_capabilities = card.capabilities or {}
        if isinstance(old_capabilities, dict):
            card.capability_streaming = old_capabilities.get('streaming', False)
            card.capability_push_notifications = old_capabilities.get('pushNotifications', False)
            card.capability_state_transition_history = old_capabilities.get('stateTransitionHistory', False)

            # 迁移 capabilities.extensions（如果存在）
            old_cap_extensions = old_capabilities.get('extensions', [])
            for order, ext in enumerate(old_cap_extensions):
                try:
                    if isinstance(ext, dict) and 'uri' in ext:
                        schema = schema_map.get(ext['uri'])
                        AgentExtension.objects.create(
                            agent_card=card,
                            uri=ext['uri'],
                            description=ext.get('description', ''),
                            required=ext.get('required', False),
                            params=ext.get('params', {}),
                            order=order,
                            schema=schema
                        )
                        migrated_count += 1
                except Exception as e:
                    print(f"警告：迁移 AgentCard {card.id} 的 capabilities.extension 时出错: {e}")
                    error_count += 1

        # 2. 迁移 domain_extensions 到 AgentExtension 模型
        old_domain_exts = card.domain_extensions or {}
        start_order = len(old_cap_extensions) if isinstance(old_capabilities, dict) else 0

        for idx, (schema_uri, params) in enumerate(old_domain_exts.items()):
            try:
                # 查找对应的 SchemaRegistry
                schema = schema_map.get(schema_uri)

                # 生成 description
                description = ""
                if schema:
                    description = schema.description or f"{schema.schema_type} {schema.version}"

                # 创建 AgentExtension
                AgentExtension.objects.create(
                    agent_card=card,
                    uri=schema_uri,
                    description=description,
                    required=False,
                    params=params,
                    order=start_order + idx,
                    schema=schema
                )
                migrated_count += 1

            except Exception as e:
                print(f"警告：迁移 AgentCard {card.id} 的 domain_extension {schema_uri} 时出错: {e}")
                error_count += 1

        # 保存更新后的 AgentCard（capability 字段）
        card.save(update_fields=[
            'capability_streaming',
            'capability_push_notifications',
            'capability_state_transition_history'
        ])

    print(f"✅ 数据迁移完成：成功迁移 {migrated_count} 个扩展，失败 {error_count} 个")


def migrate_to_extensions_backward(apps, schema_editor):
    """
    回滚：将 AgentExtension 数据恢复到 domain_extensions 和 capabilities JSONField
    """
    AgentCard = apps.get_model('documents', 'AgentCard')
    AgentExtension = apps.get_model('documents', 'AgentExtension')

    for card in AgentCard.objects.all():
        # 1. 恢复 capabilities JSONField
        capabilities = {}

        if card.capability_streaming:
            capabilities['streaming'] = True
        if card.capability_push_notifications:
            capabilities['pushNotifications'] = True
        if card.capability_state_transition_history:
            capabilities['stateTransitionHistory'] = True

        # 收集所有扩展（用于判断哪些是协议扩展，哪些是领域扩展）
        extensions_data = []
        domain_exts = {}

        for ext in card.extensions.order_by('order', 'uri'):
            ext_dict = {
                'uri': ext.uri,
                'params': ext.params
            }
            if ext.description:
                ext_dict['description'] = ext.description
            if ext.required:
                ext_dict['required'] = ext.required

            # 简单判断：以 a2a.org 开头的是协议扩展，其他的是领域扩展
            if 'a2a.org' in ext.uri:
                extensions_data.append(ext_dict)
            else:
                domain_exts[ext.uri] = ext.params

        if extensions_data:
            capabilities['extensions'] = extensions_data

        card.capabilities = capabilities
        card.domain_extensions = domain_exts

        card.save(update_fields=['capabilities', 'domain_extensions'])

    print("⚠️ 已回滚到旧的 domain_extensions 和 capabilities 结构")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_agentcard_capability_push_notifications_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_to_extensions_forward,
            migrate_to_extensions_backward
        ),
    ]
