# Generated by Django 5.2.8 on 2025-11-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_migrate_to_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentextension',
            name='order',
            field=models.IntegerField(default=0, help_text='[可选] 显示顺序（非 A2A 协议字段，仅用于 Admin 界面排序）'),
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='schema',
            field=models.ForeignKey(blank=True, help_text='[可选] 关联的 Schema 定义。\n• 领域数据扩展：选择 schema 以自动验证 params\n• 协议扩展：留空即可', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_extensions', to='documents.schemaregistry'),
        ),
    ]
