# Generated by Django 5.2.8 on 2025-11-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_update_field_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcard',
            name='preferred_transport',
            field=models.CharField(choices=[('JSONRPC', 'JSON-RPC'), ('GRPC', 'gRPC'), ('HTTP+JSON', 'HTTP+JSON')], default='JSONRPC', help_text='首选传输协议（A2A 协议 5.6.1 - 必填字段）\n• JSONRPC: JSON-RPC 2.0 over HTTP(S)\n• GRPC: gRPC protocol\n• HTTP+JSON: RESTful HTTP with JSON', max_length=32),
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='description',
            field=models.TextField(blank=True, help_text='扩展说明（可选，A2A 协议字段）。\n可从 SchemaRegistry 自动填充，或手动定制。'),
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='扩展特定的配置参数（A2A 协议字段）。\n• Data-only 扩展：结构化业务数据\n• Method 扩展：方法配置参数\n示例：{"assetId": "HPLC-001", "status": "OPERATIONAL"}'),
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='required',
            field=models.BooleanField(default=False, help_text='客户端是否必须理解此扩展（A2A 协议字段）。\n通常为 false，仅关键扩展设为 true。'),
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='schema',
            field=models.ForeignKey(blank=True, help_text='[可选] 关联的 Schema 定义（非 A2A 协议字段，内部使用）。\n用于验证 params 数据结构和自动填充 description。\n• Data-only 扩展：推荐关联 schema\n• 其他扩展：可留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_extensions', to='documents.schemaregistry'),
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='uri',
            field=models.URLField(help_text='扩展的唯一标识 URI（A2A 协议要求）。\n示例：\n• Data-only: https://your-org.com/extensions/physical-asset/v1\n• Method: https://a2a.org/extensions/task-history/v1\n• Profile: https://your-org.com/extensions/image-generation/v1', max_length=512),
        ),
    ]
