# Generated by Django 5.2.8 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_agentcard_preferred_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcard',
            name='default_input_modes',
            field=models.JSONField(blank=True, default=list, help_text="支持的输入 MIME 类型数组，如 ['text/plain', 'application/json', 'image/png']（A2A 必填，但数据库层允许暂时为空以支持渐进式录入）"),
        ),
        migrations.AlterField(
            model_name='agentcard',
            name='default_output_modes',
            field=models.JSONField(blank=True, default=list, help_text="支持的输出 MIME 类型数组，如 ['text/plain', 'application/json']（A2A 必填，但数据库层允许暂时为空以支持渐进式录入）"),
        ),
        migrations.AlterField(
            model_name='agentcard',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='AgentSkill 数组，每个 skill 包含: {name, description, inputModes?, outputModes?, parameters?}（A2A 必填，但数据库层允许暂时为空以支持渐进式录入）'),
        ),
    ]
