# Generated by Django 5.2.8 on 2025-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_allow_progressive_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentextension',
            name='uri',
            field=models.URLField(blank=True, help_text='扩展的唯一标识 URI（A2A 协议要求）。\n如果选择了 Schema，可以留空，系统会自动从 Schema 复制 URI。\n示例：\n• Data-only: https://your-org.com/extensions/physical-asset/v1\n• Method: https://a2a.org/extensions/task-history/v1\n• Profile: https://your-org.com/extensions/image-generation/v1', max_length=512),
        ),
    ]
