# Generated by Django 5.2.8 on 2025-11-12 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_agentextension_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentextension',
            name='uri',
            field=models.URLField(blank=True, help_text='【推荐留空自动填充】\n扩展的唯一标识 URI（A2A 协议要求）。\n• 如果选择了上方的 Schema，请留空此字段，系统会自动从 Schema 复制 URI\n• 如果没有选择 Schema（手动扩展），需要手动填写完整的 URI\n\n示例：\n• Data-only: https://your-org.com/extensions/physical-asset/v1\n• Method: https://a2a.org/extensions/task-history/v1\n• Profile: https://your-org.com/extensions/image-generation/v1', max_length=512),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='default_value',
            field=models.JSONField(blank=True, help_text='【仅供文档参考，不会自动应用】用于在 JSON Schema 中显示推荐的默认值，但验证时不会自动填充。示例：5 或 "ACTIVE" 或 ["tag1"]', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='enum_choices',
            field=models.JSONField(blank=True, help_text='【仅适用于 enum 类型，此类型必填此字段】\n枚举值列表（JSON 数组格式）。\n示例：["OPERATIONAL", "MAINTENANCE", "OFFLINE"]\n其他类型请勿填写，否则保存时会报错。', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='max_length',
            field=models.IntegerField(blank=True, help_text='【仅适用于 string 类型】\n字符串的最大长度限制。其他类型请勿填写，否则保存时会报错。', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='max_value',
            field=models.FloatField(blank=True, help_text='【仅适用于 integer/number 类型】\n数值的最大值限制。其他类型请勿填写，否则保存时会报错。', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='min_length',
            field=models.IntegerField(blank=True, help_text='【仅适用于 string 类型】\n字符串的最小长度限制。其他类型请勿填写，否则保存时会报错。', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='min_value',
            field=models.FloatField(blank=True, help_text='【仅适用于 integer/number 类型】\n数值的最小值限制。其他类型请勿填写，否则保存时会报错。', null=True),
        ),
        migrations.AlterField(
            model_name='schemafield',
            name='pattern',
            field=models.CharField(blank=True, help_text="【仅适用于 string 类型】\n正则表达式模式（用于验证字符串格式）。\n示例：'^[A-Z]{2,4}-\\d{3}$'（大写字母2-4位 + 连字符 + 3位数字）\n其他类型请勿填写，否则保存时会报错。", max_length=512),
        ),
        migrations.CreateModel(
            name='AgentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(db_index=True, help_text='测试用例名称', max_length=255)),
                ('is_ground_truth', models.BooleanField(db_index=True, default=False, help_text='是否为标准测试集（ground truth）')),
                ('agent_version', models.CharField(blank=True, default='*', help_text="适用的agent版本\n• 留空或'*' = 适用所有版本\n• 'latest' = 自动跟随最新版本\n• 'v1.0' = 仅适用v1.0版本", max_length=32)),
                ('query_key', models.CharField(db_index=True, help_text='查询问题标识', max_length=512)),
                ('query_description', models.TextField(blank=True, help_text='查询的详细描述或context（可选）')),
                ('query_value', models.JSONField(blank=True, default=dict, help_text='结构化查询参数（JSON格式）')),
                ('outcome_type', models.CharField(db_index=True, default='json', help_text='outcome类型。常用: json, text, binary, image, error', max_length=32)),
                ('outcome_data', models.JSONField(blank=True, help_text='存储JSON、文本或错误信息', null=True)),
                ('outcome_file', models.FileField(blank=True, help_text='存储二进制文件、图片等', max_length=512, null=True, upload_to='case_outcomes/%Y/%m/')),
                ('outcome_notes', models.TextField(blank=True, help_text='outcome的人工备注说明（可选）')),
                ('route_to', models.JSONField(blank=True, help_text='下一步路由目标（JSON格式）\n示例:\n• {"type": "agent", "agent_id": 123}\n• {"type": "human", "assignee": "user@example.com"}\n• {"type": "code", "function": "process_result"}\n• null = 终点节点', null=True)),
                ('case_score', models.FloatField(blank=True, help_text='人类对case正确性的评估打分（0.0-1.0）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_card', models.ForeignKey(blank=True, help_text='关联的AgentCard（可选）。留空表示该case尚未分配给特定agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='documents.agentcard')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='最后更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Test Case',
                'verbose_name_plural': 'Agent Test Cases',
                'db_table': 'agent_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_card', 'is_ground_truth'], name='agent_cases_agent_c_c026f1_idx'), models.Index(fields=['agent_card', 'case_score'], name='agent_cases_agent_c_4c09d6_idx'), models.Index(fields=['agent_card', 'agent_version'], name='agent_cases_agent_c_350ea5_idx'), models.Index(fields=['query_key'], name='agent_cases_query_k_1f2a9f_idx'), models.Index(fields=['outcome_type'], name='agent_cases_outcome_ab1306_idx'), models.Index(fields=['is_ground_truth'], name='agent_cases_is_grou_491191_idx')],
            },
        ),
    ]
