# Generated by Django 5.2.8 on 2025-11-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_agentextension_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcase',
            name='outcome_data',
            field=models.JSONField(blank=True, help_text='存储JSON、文本或错误信息等（JSON）', null=True),
        ),
        migrations.AlterField(
            model_name='agentcase',
            name='query_description',
            field=models.TextField(blank=True, help_text='查询的补充说明或context（可选）'),
        ),
        migrations.AlterField(
            model_name='agentcase',
            name='query_key',
            field=models.TextField(db_index=True, help_text='查询问题'),
        ),
        migrations.AlterField(
            model_name='agentcase',
            name='query_value',
            field=models.JSONField(blank=True, default=dict, help_text='结构化的查询结果（JSON）'),
        ),
    ]
